//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMIT14_T5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TEST_weatherEntities : DbContext
    {
        public TEST_weatherEntities()
            : base("name=TEST_weatherEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IOT_RawData> IOT_RawData { get; set; }
        public virtual DbSet<IOTStation> IOTStation { get; set; }
        public virtual DbSet<RawData> RawData { get; set; }
        public virtual DbSet<Station> Station { get; set; }
    }
}
