//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMIT14_T5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawData
    {
        public int Data_ID { get; set; }
        public System.DateTime DataTime { get; set; }
        public string Temperature { get; set; }
        public string Humidity { get; set; }
        public string Pressure { get; set; }
        public string H24R { get; set; }
        public string DateTempHigh { get; set; }
        public string DateTempLow { get; set; }
        public string StationID { get; set; }
    }
}
