//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMIT14_T5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public int SettingID { get; set; }
        public int AlarmTypeID { get; set; }
        public bool AlarmEnable { get; set; }
        public int AlarmCondition { get; set; }
        public int AlarmAreaID { get; set; }
        public bool AlarmAreaEnable { get; set; }
        public int DataID { get; set; }
    
        public virtual AlarmType AlarmType { get; set; }
        public virtual Area Area { get; set; }
        public virtual UserData UserData { get; set; }
    }
}
